global MAIN_DATA_DIRECTORY, PATH_TO_ORIGINAL_DATA, PATH_TO_PREPARED_DATA, PATH_TO_MEAN_DATA, SAMPLE_ID, NUM_OF_FILES

MAIN_DATA_DIRECTORY = "/home/paulo/Documents/ic_gmag/scripts/barkhausen_noises_analysis_tools_library/"

PATH_TO_ORIGINAL_DATA = f"{MAIN_DATA_DIRECTORY}Original_Py_1000nm_R798D_0.05Hz_100kHz_4MSs/"

PATH_TO_PREPARED_DATA = f"{MAIN_DATA_DIRECTORY}Prepared_Py_1000nm_R798D_0.05Hz_100kHz_4MSs/"

PATH_TO_MEAN_DATA = f"{MAIN_DATA_DIRECTORY}Means_Py_1000nm_R798D_0.05Hz_100kHz_4MSs/"

SAMPLE_ID = "R798D"

NUM_OF_FILES = 212

SAMPLING_RATE = 4e6